language: ruby
cache: bundler
rvm:
  - ruby-2.0
  - ruby-2.1
  - ruby-2.2
  - ruby-2.3.0
  - rbx
  - jruby
before_install:
  - gem update bundler
notifications:
  email:
    on_success: change
    on_failure: change
